# Build and test on both Linux and macOS
# https://docs.travis-ci.com/user/languages/objective-c/

jobs:
  include:
    - os: linux
      language: generic
      dist: trusty  # todo: try bionic
    - os: osx
      osx_image: xcode11.2
      language: swift  # equivalent to objective-c in travis

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

script:
  - mkdir Tests && cp test/LinuxMain.swift Tests/LinuxMain.swift  # swift expects this file to be in the Tests/ directory on linux
  - swift --version
  - swift build
  - swift test

# after_success:
#   - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
    on_failure: change
